CC = cc -n32 -ptused 
CCC = CC -n32 -ptused

OPT_FLAGS = -IPA -DNDEBUG

CC_FLAGS = $(OPT_FLAGS) -fullwarn -woff 1404,1209,1210 -MDupdate Makedepend 
LDLIBS = -L$(GLUI)/lib -lglui -lglut -lGL -lGLU -lXmu -lX11 -lm 

include Makefile-rules
include Makedepend
